# Configuración de la app (NO en BD)
capacidad=100

# Tarifas por hora
tarifa.auto.por_hora=1200
tarifa.moto.por_hora=700
tarifa.camioneta.por_hora=1500

# Reglas
tarifa.gracia.minutos=10
tarifa.bloque.minutos=30
tarifa.tope.diario=8000

# Nocturno (opcional)
tarifa.nocturno.habilitado=false
tarifa.nocturno.inicio.hora=22
tarifa.nocturno.fin.hora=6
tarifa.nocturno.factor=0.8

# Base de datos (editar)
db.url=jdbc:mysql://localhost:3306/parking?serverTimezone=UTC
db.user=root
db.password=root